// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.dns.upgrade_with_https_rr", true);
user_pref("app.normandy.startupRolloutPrefs.network.dns.use_https_rr_as_altsvc", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "cdeff749-0953-472f-9785-41723f50e769");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1642413934);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.migration.version", 116);
user_pref("browser.newtabpage.activity-stream.impressionId", "{bd5594a4-c912-4dea-ad38-b6f6a85b2987}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1645001227946");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1645022827946");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210823123856");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1645001226");
user_pref("browser.startup.homepage_override.buildID", "20210823123856");
user_pref("browser.startup.homepage_override.mstone", "91.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1645001226);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "91.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "KR");
user_pref("dom.push.userAgentID", "81e98e7ca46745d99e575a0bd45be2fc");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210823123856");
user_pref("extensions.lastAppVersion", "91.0.2");
user_pref("extensions.lastPlatformVersion", "91.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"9cbc0a0b-54c8-499b-89ca-018c9800e05b\",\"formautofill@mozilla.org\":\"3e3496a0-5cd7-41ea-aab2-b4c298a2c301\",\"pictureinpicture@mozilla.org\":\"82361f1e-9359-4f1c-844f-6363a169d215\",\"screenshots@mozilla.org\":\"363a3ca2-0a72-41f6-946d-df1be0f2f10c\",\"webcompat-reporter@mozilla.org\":\"813e93ad-995a-4e5c-83c3-60ff5ebd4488\",\"webcompat@mozilla.org\":\"d486ec9d-c15f-44fb-bd87-4eb186148493\",\"default-theme@mozilla.org\":\"c523798b-27c2-44d5-8c1b-9fb989f15ae3\",\"duckduckgo@search.mozilla.org\":\"49faa284-723f-4a3c-8272-fcdd399a3119\",\"wikipedia@search.mozilla.org\":\"da0780f5-e550-4ab2-8ddf-9ef41207dc5a\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "02b20317-7bbc-4eb1-9686-f7951e1bdb08");
user_pref("toolkit.startup.last_success", 1645001224);
user_pref("toolkit.telemetry.cachedClientID", "1144b7a2-2e66-49ee-a3f0-5abfddc617b4");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
